/*****************************************************************
 *  Copyright (c) Dassault Systemes. All rights reserved.        *
 *  This file is part of FMIKit. See LICENSE.txt in the project  *
 *  root for license information.                                *
 *****************************************************************/

/*
-----------------------------------------------------------
	Implementation of FMI 1.0 ME on top of C code
	generated by Simulink Coder S-function target.
-----------------------------------------------------------
*/

#include <string.h>

/* FMI memory allocation with zero initialization */
extern void* allocateMemory0(size_t nobj, size_t size);

/* Model-specific code used by wrapper, output of Simulink Coder FMI code generation */
#include "sfcn_fmi.h"

/* Forward declarations of FMI function implementation */
#include "fmi1ModelFunctions_.h"

/* -----------------------------------------------------------
   ----------------- FMI function definitions ----------------
   ----------------------------------------------------------- */

const char* fmiGetModelTypesPlatform()
{
	return fmiModelTypesPlatform;
}

const char* fmiGetVersion()
{
	return fmiVersion;
}

fmiStatus fmiSetDebugLogging(fmiComponent c, fmiBoolean loggingOn)
{
	return fmiSetDebugLogging_(c, loggingOn);
}

fmiStatus fmiSetReal(fmiComponent c, const fmiValueReference vr[], size_t nvr, const fmiReal value[])
{
	return fmiSetReal_(c, vr, nvr, value);
}

fmiStatus fmiSetInteger(fmiComponent c, const fmiValueReference vr[], size_t nvr, const fmiInteger value[])
{
	return fmiSetInteger_(c, vr, nvr, value);
}

fmiStatus fmiSetBoolean(fmiComponent c, const fmiValueReference vr[], size_t nvr, const fmiBoolean value[])
{
	return fmiSetBoolean_(c, vr, nvr, value);
}

fmiStatus fmiSetString(fmiComponent c, const fmiValueReference vr[], size_t nvr, const fmiString  value[])
{
	return fmiSetString_(c, vr, nvr, value);
}

fmiStatus fmiGetReal(fmiComponent c, const fmiValueReference vr[], size_t nvr, fmiReal value[])
{
	return fmiGetReal_(c, vr, nvr, value);
}

fmiStatus fmiGetInteger(fmiComponent c, const fmiValueReference vr[], size_t nvr, fmiInteger value[])
{
	return fmiGetInteger_(c, vr, nvr, value);
}

fmiStatus fmiGetBoolean(fmiComponent c, const fmiValueReference vr[], size_t nvr, fmiBoolean value[])
{
	return fmiGetBoolean_(c, vr, nvr, value);
}

fmiStatus fmiGetString(fmiComponent c, const fmiValueReference vr[], size_t nvr, fmiString  value[])
{
	return fmiGetString_(c, vr, nvr, value);
}

fmiComponent fmiInstantiateModel(fmiString instanceName, fmiString GUID,
								 fmiCallbackFunctions functions, fmiBoolean loggingOn)
{
	fmiComponent comp = fmiInstantiateModel_(instanceName, GUID, loggingOn, functions);
	return comp;
}

void fmiFreeModelInstance(fmiComponent c)
{
	fmiFreeModelInstance_(c);
}

fmiStatus fmiInitialize(fmiComponent c, fmiBoolean toleranceControlled, fmiReal relativeTolerance,
						fmiEventInfo* eventInfo)
{
	return fmiInitialize_(c, toleranceControlled, relativeTolerance, eventInfo);
}

fmiStatus fmiTerminate(fmiComponent c)
{
	return fmiTerminate_(c);
}

fmiStatus fmiSetTime(fmiComponent c, fmiReal time)
{
	return fmiSetTime_(c, time);
}

fmiStatus fmiSetContinuousStates(fmiComponent c, const fmiReal x[], size_t nx)
{
	return fmiSetContinuousStates_(c, x, nx);
}

fmiStatus fmiCompletedIntegratorStep(fmiComponent c, fmiBoolean* callEventUpdate)
{
	return fmiCompletedIntegratorStep_(c, callEventUpdate);
}

fmiStatus fmiGetDerivatives(fmiComponent c, fmiReal derivatives[], size_t nx)
{
	return fmiGetDerivatives_(c, derivatives, nx);
}

fmiStatus fmiGetEventIndicators(fmiComponent c, fmiReal eventIndicators[], size_t ni)
{
	return fmiGetEventIndicators_(c, eventIndicators, ni);
}

fmiStatus fmiEventUpdate(fmiComponent c, fmiBoolean intermediateResults, fmiEventInfo* eventInfo)
{
	return fmiEventUpdate_(c, intermediateResults, eventInfo);
}

fmiStatus fmiGetContinuousStates(fmiComponent c, fmiReal states[], size_t nx)
{
	return fmiGetContinuousStates_(c, states, nx);
}

fmiStatus fmiGetNominalContinuousStates(fmiComponent c, fmiReal x_nominal[], size_t nx)
{
	return fmiGetNominalContinuousStates_(c, x_nominal, nx);
}

fmiStatus fmiGetStateValueReferences(fmiComponent c, fmiValueReference vrx[], size_t nx)
{
	return fmiGetStateValueReferences_(c, vrx, nx);
}
