/*****************************************************************
 *  Copyright (c) Dassault Systemes. All rights reserved.        *
 *  This file is part of FMIKit. See LICENSE.txt in the project  *
 *  root for license information.                                *
 *****************************************************************/

/*
-----------------------------------------------------------
	Implementation of FMI 1.0 CS on top of C code
	generated by Simulink Coder S-function target.
-----------------------------------------------------------
*/

#include <string.h>

/* FMI memory allocation with zero initialization */
extern void* allocateMemory0(size_t nobj, size_t size);

/* Model-specific code used by wrapper, output of Simulink Coder FMI code generation */
#include "sfcn_fmi.h"

/* Forward declarations of FMI function implementation */
#include "fmi1Functions_.h"

/* -----------------------------------------------------------
   ----------------- FMI function definitions ----------------
   ----------------------------------------------------------- */

const char* fmiGetTypesPlatform()
{
	return fmiPlatform;
}

const char* fmiGetVersion()
{
	return fmiVersion;
}

fmiStatus fmiSetDebugLogging(fmiComponent c, fmiBoolean loggingOn)
{
	return fmiSetDebugLogging_(c, loggingOn);
}

fmiStatus fmiSetReal(fmiComponent c, const fmiValueReference vr[], size_t nvr, const fmiReal value[])
{
	return fmiSetReal_(c, vr, nvr, value);
}

fmiStatus fmiSetInteger(fmiComponent c, const fmiValueReference vr[], size_t nvr, const fmiInteger value[])
{
	return fmiSetInteger_(c, vr, nvr, value);
}

fmiStatus fmiSetBoolean(fmiComponent c, const fmiValueReference vr[], size_t nvr, const fmiBoolean value[])
{
	return fmiSetBoolean_(c, vr, nvr, value);
}

fmiStatus fmiSetString(fmiComponent c, const fmiValueReference vr[], size_t nvr, const fmiString  value[])
{
	return fmiSetString_(c, vr, nvr, value);
}

fmiStatus fmiGetReal(fmiComponent c, const fmiValueReference vr[], size_t nvr, fmiReal value[])
{
	return fmiGetReal_(c, vr, nvr, value);
}

fmiStatus fmiGetInteger(fmiComponent c, const fmiValueReference vr[], size_t nvr, fmiInteger value[])
{
	return fmiGetInteger_(c, vr, nvr, value);
}

fmiStatus fmiGetBoolean(fmiComponent c, const fmiValueReference vr[], size_t nvr, fmiBoolean value[])
{
	return fmiGetBoolean_(c, vr, nvr, value);
}

fmiStatus fmiGetString(fmiComponent c, const fmiValueReference vr[], size_t nvr, fmiString  value[])
{
	return fmiGetString_(c, vr, nvr, value);
}


fmiComponent fmiInstantiateSlave(fmiString instanceName, fmiString fmuGUID, fmiString fmuLocation, fmiString mimeType, fmiReal timeout,
                                  fmiBoolean visible, fmiBoolean interactive, fmiCallbackFunctions functions, fmiBoolean loggingOn)
{
	fmiComponent comp = fmiInstantiateSlave_(instanceName, fmuGUID, fmuLocation, mimeType, timeout, visible, interactive, functions, loggingOn);
	return comp;
}

void fmiFreeSlaveInstance(fmiComponent c)
{
	fmiFreeSlaveInstance_(c);
}

fmiStatus fmiInitializeSlave(fmiComponent c, fmiReal tStart, fmiBoolean StopTimeDefined, fmiReal tStop)
{
	return fmiInitializeSlave_(c, tStart, StopTimeDefined, tStop);
}

fmiStatus fmiTerminateSlave(fmiComponent c)
{
	return fmiTerminateSlave_(c);
}

fmiStatus fmiResetSlave(fmiComponent c)
{
	return fmiResetSlave_(c);
}

fmiStatus fmiSetRealInputDerivatives(fmiComponent c, const  fmiValueReference vr[], size_t nvr, const  fmiInteger order[], const  fmiReal value[])
{
	return fmiSetRealInputDerivatives_(c, vr, nvr, order, value);
}

fmiStatus fmiGetRealOutputDerivatives(fmiComponent c, const   fmiValueReference vr[], size_t  nvr, const   fmiInteger order[], fmiReal value[])
{
	return fmiGetRealOutputDerivatives_(c, vr, nvr, order, value);
}

fmiStatus fmiCancelStep(fmiComponent c)
{
	return fmiCancelStep_(c);
}

fmiStatus fmiDoStep(fmiComponent c, fmiReal currentCommunicationPoint, fmiReal communicationStepSize, fmiBoolean newStep)
{
	return fmiDoStep_(c, currentCommunicationPoint, communicationStepSize, newStep);
}

fmiStatus fmiGetStatus(fmiComponent c, const fmiStatusKind s, fmiStatus*  value)
{
	return fmiGetStatus_(c, s, value);
}

fmiStatus fmiGetRealStatus(fmiComponent c, const fmiStatusKind s, fmiReal* value)
{
	return fmiGetRealStatus_(c, s, value);
}

fmiStatus fmiGetIntegerStatus(fmiComponent c, const fmiStatusKind s, fmiInteger* value)
{
	return fmiGetIntegerStatus_(c, s, value);
}

fmiStatus fmiGetBooleanStatus(fmiComponent c, const fmiStatusKind s, fmiBoolean* value)
{
	return fmiGetBooleanStatus_(c, s, value);
}

fmiStatus fmiGetStringStatus(fmiComponent c, const fmiStatusKind s, fmiString* value)
{
	return fmiGetStringStatus_(c, s, value);
}
