/*****************************************************************
 *  Copyright (c) Dassault Systemes. All rights reserved.        *
 *  This file is part of FMIKit. See LICENSE.txt in the project  *
 *  root for license information.                                *
 *****************************************************************/

/*
-----------------------------------------------------------
	Implementation of FMI 2.0 CS on top of C code
	generated by Simulink Coder S-function target.
-----------------------------------------------------------
*/

#include <stddef.h>

/* FMI memory allocation with zero initialization */
extern void* allocateMemory0(size_t nobj, size_t size);

/* Model-specific code used by wrapper, output of Simulink Coder FMI code generation */
#include "sfcn_fmi.h"
