function generators = grtfmi_cmake_generators()

if ismac
    generators = 'Unix Makefiles|Xcode';
elseif isunix
    generators = 'Unix Makefiles';
elseif ispc
    generators = ['Visual Studio 17 2022|' ...
                  'Visual Studio 16 2019|' ...
                  'Visual Studio 15 2017|' ...
                  'Visual Studio 14 2015|' ...
                  'Visual Studio 12 2013|' ...
                  'Visual Studio 11 2012|' ...
                  'Visual Studio 10 2010|' ...
                  'Visual Studio 9 2008'];
else
    error('Platform not supported.');
end
